[package]
name = "phone_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.7"
dbus-crossroads = "0.5.2"
dbus-tokio = "0.7.6"
futures = "0.3.30"
futures-util = "0.3.30"
notify-rust = "4.11.3"
tokio = { version = "1.40.0", features = ["rt", "macros"] }
